from .permissions import check_for_access

#   - Can this user create a ticket?
#   - What default status should a new ticket have?
#   - Should this update be allowed?
#   - What fields are generated by the backend?
#   - Should we call an LLM or background job?
#   - Should we hash a password before saving?
#   - Should we return 404, 409, or success?