"""initial schema

Revision ID: 996924fc3d59
Revises: 
Create Date: 2026-08-09 11:23:22.310471

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996924fc3d59'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'AGENT', 'AGENT_READONLY', 'USER', 'GUEST', 'BOT', 'API', name='role'), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_status', sa.Enum('ACTIVE', 'DELETED', 'BANNED', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('agent_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'PAUSED', 'OFFLINE', name='availabilitystatus'), nullable=False),
    sa.Column('availability_reason', sa.String(length=50), nullable=True),
    sa.Column('availability_note', sa.String(length=255), nullable=True),
    sa.Column('unavailable_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_active_tickets', sa.Integer(), nullable=False),
    sa.Column('last_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('TICKET', 'USER', 'AGENT_PROFILE', 'DEPARTMENT', 'SKILL', 'REFRESH_SESSION', 'COMMENT', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.Enum('HUMAN', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.Enum('TICKET_CREATED', 'TICKET_CLAIMED', 'TICKET_ASSIGNED', 'TICKET_REASSIGNED', 'TICKET_DELETED', 'TICKETS_BULK_DELETED', 'TICKET_STATUS_CHANGED', 'TICKET_UPDATED', 'USER_CREATED', 'USER_BULK_DELETED', 'USER_UPDATED', 'USER_DELETED', 'AGENT_AVAILABILITY_CHANGED', 'AGENT_PROFILE_UPDATED', 'DEPARTMENT_CREATED', 'DEPARTMENT_UPDATED', 'DEPARTMENT_ARCHIVED', 'SKILL_CREATED', 'SKILL_UPDATED', 'SKILL_ARCHIVED', 'TICKET_OVERDUE', 'REFRESH_SESSION_CREATED', 'REFRESH_SESSION_REVOKED', 'REFRESH_SESSION_ROTATED', 'COMMENT_CREATED', 'COMMENT_UPDATED', 'COMMENT_DELETED', name='eventtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('metadata', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(actor_type = 'HUMAN' AND actor_user_id IS NOT NULL) OR (actor_type = 'SYSTEM' AND actor_user_id IS NULL)", name='ck_events_actor_contract'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('refresh_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=32000), nullable=False),
    sa.Column('category', sa.Enum('API_ERROR', 'AUTHENTICATION', 'MODEL_OUTPUT', 'RAG_RETRIEVAL', 'AGENT_WORKFLOW', 'PERFORMANCE', 'BILLING', 'ACCOUNT_ACCESS', 'DOCUMENTATION', 'FEATURE_REQUEST', name='category'), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('creator_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'OPEN', 'PENDING', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REOPENED', name='status'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'NORMAL', 'LOW', name='priority'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_skills',
    sa.Column('agent_user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_user_id'], ['agent_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('agent_user_id', 'skill_id')
    )
    op.create_table('analysis_result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('input_snapshot', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'PENDING'\n                AND summary IS NULL\n                AND error_code IS NULL\n                AND error_message IS NULL\n                AND completed_at IS NULL\n                AND attempt_count < 3\n            )\n            OR (\n                status = 'RUNNING'\n                AND summary IS NULL\n                AND error_code IS NULL\n                AND error_message IS NULL\n                AND started_at IS NOT NULL\n                AND completed_at IS NULL\n                AND attempt_count BETWEEN 1 AND 3\n            )\n            OR (\n                status = 'COMPLETED'\n                AND summary IS NOT NULL\n                AND error_code IS NULL\n                AND error_message IS NULL\n                AND started_at IS NOT NULL\n                AND completed_at IS NOT NULL\n                AND attempt_count BETWEEN 1 AND 3\n            )\n            OR (\n                status = 'FAILED'\n                AND summary IS NULL\n                AND error_code IS NOT NULL\n                AND error_message IS NOT NULL\n                AND completed_at IS NOT NULL\n            )\n            ", name='ck_analysis_result_lifecycle'),
    sa.CheckConstraint('attempt_count >= 0 AND attempt_count <= 3', name='ck_analysis_result_attempt_count'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_analysis_result_active_ticket', 'analysis_result', ['ticket_id'], unique=True, sqlite_where=sa.text("ticket_id IS NOT NULL AND status IN ('PENDING', 'RUNNING')"), postgresql_where=sa.text("ticket_id IS NOT NULL AND status IN ('PENDING', 'RUNNING')"))
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'INTERNAL', 'PRIVATE_TO_MANAGER', name='visibility'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('attachments_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('WEB', 'API', 'EMAIL', 'BOT', 'SYSTEM', name='source'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_skills',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_skills')
    op.drop_table('comments')
    op.drop_index('uq_analysis_result_active_ticket', table_name='analysis_result', sqlite_where=sa.text("ticket_id IS NOT NULL AND status IN ('PENDING', 'RUNNING')"), postgresql_where=sa.text("ticket_id IS NOT NULL AND status IN ('PENDING', 'RUNNING')"))
    op.drop_table('analysis_result')
    op.drop_table('agent_skills')
    op.drop_table('tickets')
    op.drop_table('refresh_sessions')
    op.drop_table('events')
    op.drop_table('agent_profiles')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('departments')
    # ### end Alembic commands ###
